# Generated by Django 4.2 on 2023-08-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_header_image',
            field=models.ImageField(default='blog_headers/hero_1.jpg', upload_to='blog_headers/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
