# Generated by Django 4.2.3 on 2023-09-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment_delete_comments_alter_blog_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
